from PyQt5 import QtCore, QtGui, QtWidgets
import math


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.suma = QtWidgets.QPushButton(self.centralwidget)
        self.suma.setGeometry(QtCore.QRect(190, 130, 80, 25))
        self.suma.setObjectName("pushButton")
        self.resta = QtWidgets.QPushButton(self.centralwidget)
        self.resta.setGeometry(QtCore.QRect(270, 130, 80, 25))
        self.resta.setObjectName("pushButton_2")
        self.multiplicacion = QtWidgets.QPushButton(self.centralwidget)
        self.multiplicacion.setGeometry(QtCore.QRect(220, 160, 100, 25))
        self.multiplicacion.setObjectName("pushButton_3")
        self.cociente = QtWidgets.QPushButton(self.centralwidget)
        self.cociente.setGeometry(QtCore.QRect(190, 190, 80, 25))
        self.cociente.setObjectName("pushButton_4")
        self.residuo = QtWidgets.QPushButton(self.centralwidget)
        self.residuo.setGeometry(QtCore.QRect(270, 190, 80, 25))
        self.residuo.setObjectName("pushButton_5")
        self.inputA = QtWidgets.QLineEdit(self.centralwidget)
        self.inputA.setGeometry(QtCore.QRect(30, 80, 200, 25))
        self.inputA.setObjectName("lineEdit")
        self.inputB = QtWidgets.QLineEdit(self.centralwidget)
        self.inputB.setGeometry(QtCore.QRect(330, 80, 200, 25))
        self.inputB.setObjectName("lineEdit_2")
        self.operacion = QtWidgets.QLabel(self.centralwidget)
        self.operacion.setGeometry(QtCore.QRect(260, 80, 50, 25))
        self.operacion.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 80, 20, 25))
        self.label_2.setObjectName("label_2")
        self.resultadoA = QtWidgets.QLabel(self.centralwidget)
        self.resultadoA.setGeometry(QtCore.QRect(590, 80, 200, 25))
        self.resultadoA.setObjectName("label_3")
        self.seno = QtWidgets.QPushButton(self.centralwidget)
        self.seno.setGeometry(QtCore.QRect(150, 340, 89, 25))
        self.seno.setObjectName("pushButton_6")
        self.coseno = QtWidgets.QPushButton(self.centralwidget)
        self.coseno.setGeometry(QtCore.QRect(240, 340, 89, 25))
        self.coseno.setObjectName("pushButton_7")
        self.tangente = QtWidgets.QPushButton(self.centralwidget)
        self.tangente.setGeometry(QtCore.QRect(330, 340, 89, 25))
        self.tangente.setObjectName("pushButton_8")
        self.cosecante = QtWidgets.QPushButton(self.centralwidget)
        self.cosecante.setGeometry(QtCore.QRect(150, 370, 89, 25))
        self.cosecante.setObjectName("pushButton_9")
        self.secante = QtWidgets.QPushButton(self.centralwidget)
        self.secante.setGeometry(QtCore.QRect(240, 370, 89, 25))
        self.secante.setObjectName("pushButton_10")
        self.cotangente = QtWidgets.QPushButton(self.centralwidget)
        self.cotangente.setGeometry(QtCore.QRect(330, 370, 89, 25))
        self.cotangente.setObjectName("pushButton_11")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 510, 160, 25))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 450, 160, 25))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 480, 160, 25))
        self.label_6.setObjectName("label_6")
        self.inputC = QtWidgets.QLineEdit(self.centralwidget)
        self.inputC.setGeometry(QtCore.QRect(185, 300, 200, 25))
        self.inputC.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 40, 170, 25))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(185, 260, 200, 25))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 540, 160, 25))
        self.label_9.setObjectName("label_9")
        self.resultadob = QtWidgets.QLabel(self.centralwidget)
        self.resultadob.setGeometry(QtCore.QRect(440, 300, 200, 25))
        self.resultadob.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 300, 20, 25))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 420, 221, 151))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Laboratorio_2/Imagenes/images.png"))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laboratorio 2 - Primer punto"))
        self.suma.setText(_translate("MainWindow", "Suma"))
        self.resta.setText(_translate("MainWindow", "Resta"))
        self.multiplicacion.setText(_translate("MainWindow", "Multiplicación"))
        self.cociente.setText(_translate("MainWindow", "Cociente"))
        self.residuo.setText(_translate("MainWindow", "Residuo"))
        self.operacion.setText(_translate("MainWindow", "Op"))
        self.label_2.setText(_translate("MainWindow", "="))
        self.resultadoA.setText(_translate("MainWindow", "Resultado"))
        self.seno.setText(_translate("MainWindow", "Seno"))
        self.coseno.setText(_translate("MainWindow", "Coseno"))
        self.tangente.setText(_translate("MainWindow", "Tangente"))
        self.cosecante.setText(_translate("MainWindow", "Cosecante"))
        self.secante.setText(_translate("MainWindow", "Secante"))
        self.cotangente.setText(_translate("MainWindow", "Cotangente"))
        self.label_4.setText(_translate("MainWindow", "Juan Sebastian Torres"))
        self.label_5.setText(_translate("MainWindow", "Juan Camilo Alberto"))
        self.label_6.setText(_translate("MainWindow", "Sergio Andres Lopez"))
        self.label_9.setText(_translate("MainWindow", "Steven Santana"))
        self.label_7.setText(_translate("MainWindow", "Operaciones aritmeticas"))
        self.label_8.setText(_translate("MainWindow", "Operaciones trigonometricas"))
        self.resultadob.setText(_translate("MainWindow", "Resultado"))
        self.label_10.setText(_translate("MainWindow", "="))

        self.suma.clicked.connect(self.Suma)
        self.resta.clicked.connect(self.Resta)
        self.multiplicacion.clicked.connect(self.Multiplicacion)
        self.cociente.clicked.connect(self.Cociente)
        self.residuo.clicked.connect(self.Residuo)
        self.seno.clicked.connect(self.Sen)
        self.coseno.clicked.connect(self.Cos)
        self.tangente.clicked.connect(self.Tan)
        self.cotangente.clicked.connect(self.Ctn)
        self.secante.clicked.connect(self.Sec)
        self.cosecante.clicked.connect(self.Csc)

    def Suma(self):
        a = self.inputA.text()
        b = self.inputB.text()
        c = float(a) + float(b)
        self.operacion.setText("+")
        self.resultadoA.setText(str(c))

    def Resta(self):
        a = self.inputA.text()
        b = self.inputB.text()
        c = float(a) - float(b)
        self.operacion.setText("-")
        self.resultadoA.setText(str(c))

    def Multiplicacion(self):
        a = self.inputA.text()
        b = self.inputB.text()
        c = float(a) * float(b)
        self.operacion.setText("x")
        self.resultadoA.setText(str(c))

    def Cociente(self):
        a = self.inputA.text()
        b = self.inputB.text()
        c = float(a) / float(b)
        self.operacion.setText("/")
        self.resultadoA.setText(str(c))

    def Residuo(self):
        a = self.inputA.text()
        b = self.inputB.text()
        c = float(a) % float(b)
        self.operacion.setText("%")
        self.resultadoA.setText(str(c))

    def Sen(self):
        d = self.inputC.text()
        e = math.sin(math.radians(int(d)))
        self.resultadob.setText(str(e))
        

    def Cos(self):
        d = self.inputC.text()
        e = math.cos(math.radians(int(d)))
        self.resultadob.setText(str(e))

    def Tan(self):
        d = self.inputC.text()
        e = math.tan(math.radians(int(d)))
        self.resultadob.setText(str(e))

    def Ctn(seslf):
        d = seslf.inputC.text()
        e = (1 / math.tan(math.radians(int(d))))
        seslf.resultadob.setText(str(e))

    def Sec(seslf):
        d = seslf.inputC.text()
        e = (1 / math.cos(math.radians(int(d))))
        seslf.resultadob.setText(str(e))

    def Csc(seslf):
        d = seslf.inputC.text()
        e = (1 / math.sin(math.radians(int(d))))
        seslf.resultadob.setText(str(e))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())